name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Prepare archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/md-task dist/
          cp README.md LICENSE* dist/ || true
          cd dist
          tar czf ../md-task-${{ matrix.name }}.tar.gz .
      
      - name: Prepare archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/md-task.exe dist/
          cp README.md LICENSE* dist/ || true
          Compress-Archive -Path dist/* -DestinationPath md-task-${{ matrix.name }}.zip
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: md-task-${{ matrix.name }}
          path: |
            md-task-${{ matrix.name }}.tar.gz
            md-task-${{ matrix.name }}.zip
  
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: md-task-*/md-task-*.{tar.gz,zip}
          generate_release_notes: true